import { useEffect, useState } from "react";
import api from "../api/axios";
import { employeeAreas } from "../data/employeeAreas";
import { getStoredUser, isAdmin } from "../utils/auth";

const normalize = (value = "") => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/\s+/g, " ");
const userDetails = () => { const user=getStoredUser(); const name=[user?.name,user?.lastname].filter(Boolean).join(" "); return {name,area:employeeAreas[normalize(name)]||""}; };
const labels={temporary_loan:"Préstamo temporal",permanent_replacement:"Cambio definitivo",pending:"Pendiente",delivered:"Entregado",rejected:"Rechazado",returned:"Devuelto"};

export default function Requests(){
 const admin=isAdmin(); const [{name,area}]=useState(userDetails); const [items,setItems]=useState([]); const [requests,setRequests]=useState([]); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [form,setForm]=useState({item_id:"",quantity:1,request_type:"temporary_loan",expected_return_datetime:"",notes:""});
 const selectedItem=items.find(item=>String(item.id)===String(form.item_id)); const exceedsAvailable=Boolean(selectedItem)&&Number(form.quantity)>Number(selectedItem.available_quantity);
 const load=async()=>{try{const [itemsRes,requestsRes]=await Promise.all([admin?Promise.resolve({data:[]}):api.get("/inventory/items"),api.get(admin?"/inventory/requests":"/inventory/requests/mine")]);setItems(itemsRes.data);setRequests(requestsRes.data);}catch(e){setError(e.response?.data?.message||"No se pudieron cargar las solicitudes.");}};
 useEffect(()=>{let active=true;const loadInitial=async()=>{try{const [itemsRes,requestsRes]=await Promise.all([admin?Promise.resolve({data:[]}):api.get("/inventory/items"),api.get(admin?"/inventory/requests":"/inventory/requests/mine")]);if(active){setItems(itemsRes.data);setRequests(requestsRes.data);}}catch(e){if(active)setError(e.response?.data?.message||"No se pudieron cargar las solicitudes.");}};loadInitial();return()=>{active=false;};},[admin]);
 const submit=async(e)=>{e.preventDefault();setError("");try{await api.post("/inventory/requests",{...form,item_id:Number(form.item_id),quantity:Number(form.quantity),position:area});setMessage("Solicitud registrada y pendiente de aprobación.");setForm({item_id:"",quantity:1,request_type:"temporary_loan",expected_return_datetime:"",notes:""});load();}catch(e){setError(e.response?.data?.message||"No se pudo registrar la solicitud.");}};
 const action=async(id,kind)=>{try{if(kind==="reject"){const reason=window.prompt("Motivo del rechazo (opcional):");await api.patch(`/inventory/requests/${id}/reject`,{reason});}else if(kind==="deliver"){const request=requests.find(r=>r.id===id);const previous_component_received=request.request_type==="permanent_replacement"&&window.confirm("¿Confirmas que recibiste el componente anterior?");if(request.request_type==="permanent_replacement"&&!previous_component_received)return;await api.patch(`/inventory/requests/${id}/deliver`,{previous_component_received});}else await api.patch(`/inventory/requests/${id}/return`);setMessage("Solicitud actualizada.");load();}catch(e){setError(e.response?.data?.message||"No se pudo actualizar la solicitud.");}};
 if(admin)return <main className="app-page"><h1 className="page-title">Solicitudes</h1>{message&&<div className="alert alert-success">{message}</div>}{error&&<div className="alert alert-danger">{error}</div>}<div className="card"><div className="table-responsive"><table className="table mb-0"><thead><tr><th>Solicitante</th><th>Artículo</th><th>Tipo</th><th>Estado</th><th /></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{r.requested_by}<small className="d-block text-muted">{r.position}</small></td><td>{r.item_name} × {r.quantity}</td><td>{labels[r.request_type]}</td><td>{labels[r.status]}</td><td className="text-end">{r.status==="pending"&&<><button className="btn btn-sm btn-success me-1" onClick={()=>action(r.id,"deliver")}>{r.request_type==="permanent_replacement"?"Recibir y entregar":"Aprobar y entregar"}</button><button className="btn btn-sm btn-outline-danger" onClick={()=>action(r.id,"reject")}>Rechazar</button></>}{r.status==="delivered"&&r.request_type==="temporary_loan"&&<button className="btn btn-sm btn-outline-primary" onClick={()=>action(r.id,"return")}>Registrar devolución</button>}</td></tr>)}</tbody></table></div></div></main>;
 return <main className="app-page"><h1 className="page-title">Nueva solicitud</h1>{message&&<div className="alert alert-success">{message}</div>}{error&&<div className="alert alert-danger">{error}</div>}<form className="card card-body row g-3" onSubmit={submit}><div className="col-md-6"><label className="form-label">Solicitante</label><input className="form-control" value={name} readOnly /></div><div className="col-md-6"><label className="form-label">Área</label><input className="form-control" value={area} readOnly required /></div><div className="col-12"><label className="form-label">Tipo</label><select className="form-select" value={form.request_type} onChange={e=>setForm({...form,request_type:e.target.value})}><option value="temporary_loan">Préstamo temporal</option><option value="permanent_replacement">Cambio definitivo</option></select></div><div className="col-md-8"><label className="form-label">Artículo</label><select className="form-select" required value={form.item_id} onChange={e=>setForm({...form,item_id:e.target.value})}><option value="">Selecciona un artículo</option>{items.map(i=><option key={i.id} value={i.id} disabled={!i.available_quantity}>{i.name} — {i.available_quantity} disponibles</option>)}</select></div><div className="col-md-4"><label className="form-label">Cantidad</label><input className={`form-control ${exceedsAvailable?"is-invalid":""}`} type="number" min="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/>{exceedsAvailable&&<div className="invalid-feedback d-block" role="alert">La cantidad supera las {selectedItem.available_quantity} unidades disponibles.</div>}</div>{form.request_type==="temporary_loan"&&<div className="col-12"><label className="form-label">Devolución esperada</label><input className="form-control" type="datetime-local" required value={form.expected_return_datetime} onChange={e=>setForm({...form,expected_return_datetime:e.target.value})}/></div>}<div className="col-12"><label className="form-label">Motivo</label><textarea className="form-control" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="col-12"><button className="btn btn-primary" disabled={exceedsAvailable}>Enviar solicitud</button></div></form></main>;
}
