export default function UserRequestForm({ name, area, items, form, setForm, selectedItem, exceedsAvailable, submit, message, error }) {
  return <main className="app-page">
    <div className="row justify-content-center"><div className="col-xl-9">
      <div className="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p className="page-kicker mb-2">Servicios de tecnología</p><h1 className="page-title mb-2">Nueva solicitud</h1><p className="page-subtitle mb-0">Solicita un periférico o un cambio de componente para continuar tu trabajo.</p></div><span className="status-pill"><i className="bi bi-headset me-2" />Atención de Sistemas</span></div>
      {message && <div className="alert alert-success" role="status">{message}</div>}
      {error && <div className="alert alert-danger" role="alert">{error}</div>}
      <form className="card request-form-card" onSubmit={submit}>
        <div className="card-body p-4 p-lg-5">
          <div className="request-section-heading"><span className="request-section-icon"><i className="bi bi-person-check" /></span><div><h2 className="h5 mb-1">Tus datos</h2><p className="text-muted small mb-0">Se completan automáticamente con tu perfil.</p></div></div>
          <div className="row g-3 mb-4"><div className="col-md-6"><label className="form-label" htmlFor="requester-name">Solicitante</label><input id="requester-name" className="form-control" value={name} readOnly /></div><div className="col-md-6"><label className="form-label" htmlFor="requester-area">Área</label><input id="requester-area" className="form-control" value={area} readOnly required /></div></div>
          <div className="request-section-heading"><span className="request-section-icon"><i className="bi bi-box-seam" /></span><div><h2 className="h5 mb-1">¿Qué necesitas?</h2><p className="text-muted small mb-0">Indica el elemento y el tipo de solicitud.</p></div></div>
          <div className="row g-3"><div className="col-md-5"><label className="form-label" htmlFor="request-type">Tipo de solicitud</label><select id="request-type" className="form-select" value={form.request_type} onChange={(event) => setForm({ ...form, request_type: event.target.value })}><option value="temporary_loan">Préstamo temporal</option><option value="permanent_replacement">Cambio definitivo</option></select></div><div className="col-md-7"><label className="form-label" htmlFor="request-item">Elemento</label><select id="request-item" className="form-select" required value={form.item_id} onChange={(event) => setForm({ ...form, item_id: event.target.value })}><option value="">Selecciona un elemento</option>{items.map((item) => <option key={item.id} value={item.id} disabled={!item.available_quantity}>{item.name} — {item.available_quantity} disponibles</option>)}</select></div><div className="col-md-4"><label className="form-label" htmlFor="request-quantity">Cantidad</label><input id="request-quantity" className={`form-control ${exceedsAvailable ? "is-invalid" : ""}`} type="number" min="1" required value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} />{exceedsAvailable && <div className="invalid-feedback d-block" role="alert">La cantidad supera las {selectedItem.available_quantity} disponibles.</div>}</div>{form.request_type === "temporary_loan" && <div className="col-md-8"><label className="form-label" htmlFor="request-return">Devolución esperada</label><input id="request-return" className="form-control" type="datetime-local" required value={form.expected_return_datetime} onChange={(event) => setForm({ ...form, expected_return_datetime: event.target.value })} /></div>}<div className="col-12"><label className="form-label" htmlFor="request-notes">Motivo o detalle adicional</label><textarea id="request-notes" className="form-control" rows="3" placeholder="Cuéntanos brevemente qué necesitas y por qué." value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></div></div>
        </div><div className="card-footer bg-transparent border-0 px-4 px-lg-5 pb-4 pb-lg-5"><button className="btn btn-primary" type="submit" disabled={exceedsAvailable}><i className="bi bi-send me-2" />Enviar solicitud</button></div>
      </form>
    </div></div>
  </main>;
}
